name: afinc-inventory-client-prod
networks:
  afinc-inventory-prod-network:
    driver: bridge 

services:
  afinc.inventory.client.site-prod:
    container_name: afinc.inventory.site-prod
    depends_on:
      - "afinc.inventory.client.api-prod"
    build:
      context: .
      dockerfile: src/afincinventory.site/Dockerfile
      args:
      - AFINC_INVENTORY_BACKEND_URL=https://prod-afinc-inventory-api.loca.lt
    volumes:
      - ./src:/app/src
    ports:
      - "5890:3000"
    networks:
      - afinc-inventory-prod-network  
  afinc.inventory.client.api-prod:
    container_name: afinc.inventory.api-prod    
    restart: on-failure
    depends_on:
      afinc.inventory.client.db-prod:
       condition: service_started
       restart: true
    build:
      context: .
      dockerfile: src/Afinc.Inventory.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=host=afinc.inventory.client.db-prod;port=5432;database=AfincInventoryClient;username=postgres;password=afincsol@1
    ports:
      - "5891:80"
    networks:
      - afinc-inventory-prod-network
      
  afinc.inventory.client.db-prod:
    container_name: afinc.inventory.client.db-prod
    image: postgres:latest
    ports:
      - "5892:5432"
    restart: on-failure
    volumes:
      - afinc.inventoy.client.data-prod:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: afincsol@1
      POSTGRES_DB: AfincInventoryClient
    networks:
      - afinc-inventory-prod-network
volumes:
  afinc.inventoy.client.data-prod:
   driver: local
   driver_opts:
      o: bind
      type: none
      device: ../data/afinc-inventoy-client-prod
